### ISSUE TITLE
No hope in Expo? 😢

### ISSUE THREAD

**Issue by devhyunjae** [a7med-mahmoud/react-native-prevent-screenshots#1]
Steps to reproduce

1. expo init
2. code below
```javascript
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { useEffect } from 'react';
import { Button, StyleSheet, Text, View } from 'react-native';
import { withPreventScreenshots, PreventScreenshots } from 'react-native-prevent-screenshots';

const App = () => {
  useEffect(() => {
    PreventScreenshots.start();
  }, [])
  return (
    <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default withPreventScreenshots(App);
```
3. throws this error
```
TypeError: null is not an object (evaluating 'Native.start')

This error is located at:
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:43:2 in showErrorDialog

TypeError: null is not an object (evaluating 'Native.start')

This error is located at:
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```

I also copy pasted your example code, but throws the same error

**Comment by a7medev** [comment]
I'll work on support for Expo custom dev client, but unfortunately it's not possible with a fully managed workflow.

**Comment by a7medev** [comment]
I tested it, it works well with Expo custom managed workflows, to enable it you can run:

```sh
expo run:android
```

Which adds the native android folder and allows you to use native code (or libraries with native code like this one) without ejecting from Expo.

> NOTE: You don't have to add the native files for iOS for now because `react-native-prevent-screenshots` uses the React Native `AppState` API on iOS.
